services:
  db:
    image: postgres:16
    container_name: core_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: core_data
      POSTGRES_USER: db_service
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - core_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_service -d core_data" ]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: core_postgres_pgadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: core_data@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - core_pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: core_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:5063"
    ports:
      - "5063:5063"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: core_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4200:4200"

volumes:
  core_pg_data:
  core_pgadmin_data:
